# Generated by Django 5.1.6 on 2025-03-03 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Body of the comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time stamp of comment creation'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(help_text='The discussion this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussion.discussion'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Foreign key of the parent comment (if it is a reply to another comment), null if it is a top level comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussion.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(help_text='Author of the Comment', max_length=100),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto-generated timestamp of creation time'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(help_text='The actual discussion topic or title', max_length=280),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='user',
            field=models.CharField(help_text='Author of the discussion', max_length=100),
        ),
    ]
